blueprint:
  name: Flexible Multi-Entity Status Notification
  description: Monitor any entities for specific statuses and send consolidated notifications
  domain: automation
  input:
    notification_service:
      name: Notification Service
      description: The notification service to use
      selector:
        text:
      default: "notify.notify"
    
    notification_title:
      name: Notification Title
      description: Title for the notification
      selector:
        text:
      default: "Entity Status Alert"
    
    # Entity 1 Configuration
    entity1_enable:
      name: Enable Entity 1
      description: Monitor the first entity/group
      selector:
        boolean:
      default: true
    
    entity1_target:
      name: Entity 1
      description: Select any entity or group to monitor
      selector:
        entity: {}
      default: ""
    
    entity1_status:
      name: Entity 1 Status
      description: Status to check for
      selector:
        text:
      default: "unavailable"
    
    entity1_label:
      name: Entity 1 Label
      description: Label for notification
      selector:
        text:
      default: "ENTITY 1 ALERTS"
    
    entity1_icon:
      name: Entity 1 Icon
      description: Icon/emoji for notification
      selector:
        text:
      default: "🔔"
    
    # Entity 2 Configuration
    entity2_enable:
      name: Enable Entity 2
      description: Monitor the second entity/group
      selector:
        boolean:
      default: false
    
    entity2_target:
      name: Entity 2
      description: Select any entity or group to monitor
      selector:
        entity: {}
      default: ""
    
    entity2_status:
      name: Entity 2 Status
      description: Status to check for
      selector:
        text:
      default: "on"
    
    entity2_label:
      name: Entity 2 Label
      description: Label for notification
      selector:
        text:
      default: "ENTITY 2 ALERTS"
    
    entity2_icon:
      name: Entity 2 Icon
      description: Icon/emoji for notification
      selector:
        text:
      default: "⚡"
    
    # Entity 3 Configuration
    entity3_enable:
      name: Enable Entity 3
      description: Monitor the third entity/group
      selector:
        boolean:
      default: false
    
    entity3_target:
      name: Entity 3
      description: Select any entity or group to monitor
      selector:
        entity: {}
      default: ""
    
    entity3_status:
      name: Entity 3 Status
      description: Status to check for
      selector:
        text:
      default: "unknown"
    
    entity3_label:
      name: Entity 3 Label
      description: Label for notification
      selector:
        text:
      default: "ENTITY 3 ALERTS"
    
    entity3_icon:
      name: Entity 3 Icon
      description: Icon/emoji for notification
      selector:
        text:
      default: "📡"

trigger:
  - platform: state
    entity_id: !input entity1_target
    enabled: !input entity1_enable
  - platform: state
    entity_id: !input entity2_target
    enabled: !input entity2_enable
  - platform: state
    entity_id: !input entity3_target
    enabled: !input entity3_enable

condition:
  - condition: template
    value_template: >
      {% set matching = namespace(found=false) %}
      {% set entity1_enable = entity1_enable %}
      {% set entity1_target = entity1_target %}
      {% set entity1_status = entity1_status %}
      {% set entity2_enable = entity2_enable %}
      {% set entity2_target = entity2_target %}
      {% set entity2_status = entity2_status %}
      {% set entity3_enable = entity3_enable %}
      {% set entity3_target = entity3_target %}
      {% set entity3_status = entity3_status %}
      
      {% if entity1_enable and entity1_target != "" %}
        {% if entity1_target.startswith('group.') %}
          {% if expand(entity1_target) | selectattr('state', 'eq', entity1_status) | list | length > 0 %}
            {% set matching.found = true %}
          {% endif %}
        {% else %}
          {% if states(entity1_target) == entity1_status %}
            {% set matching.found = true %}
          {% endif %}
        {% endif %}
      {% endif %}
      
      {% if entity2_enable and entity2_target != "" %}
        {% if entity2_target.startswith('group.') %}
          {% if expand(entity2_target) | selectattr('state', 'eq', entity2_status) | list | length > 0 %}
            {% set matching.found = true %}
          {% endif %}
        {% else %}
          {% if states(entity2_target) == entity2_status %}
            {% set matching.found = true %}
          {% endif %}
        {% endif %}
      {% endif %}
      
      {% if entity3_enable and entity3_target != "" %}
        {% if entity3_target.startswith('group.') %}
          {% if expand(entity3_target) | selectattr('state', 'eq', entity3_status) | list | length > 0 %}
            {% set matching.found = true %}
          {% endif %}
        {% else %}
          {% if states(entity3_target) == entity3_status %}
            {% set matching.found = true %}
          {% endif %}
        {% endif %}
      {% endif %}
      
      {{ matching.found }}

action:
  - service: !input notification_service
    data:
      title: !input notification_title
      message: >
        {% set alerts = [] %}
        {% set entity1_enable = entity1_enable %}
        {% set entity1_target = entity1_target %}
        {% set entity1_status = entity1_status %}
        {% set entity1_label = entity1_label %}
        {% set entity1_icon = entity1_icon %}
        {% set entity2_enable = entity2_enable %}
        {% set entity2_target = entity2_target %}
        {% set entity2_status = entity2_status %}
        {% set entity2_label = entity2_label %}
        {% set entity2_icon = entity2_icon %}
        {% set entity3_enable = entity3_enable %}
        {% set entity3_target = entity3_target %}
        {% set entity3_status = entity3_status %}
        {% set entity3_label = entity3_label %}
        {% set entity3_icon = entity3_icon %}
        
        {# Check Entity 1 #}
        {% if entity1_enable and entity1_target != "" %}
          {% if entity1_target.startswith('group.') %}
            {% set matching_entities = expand(entity1_target) | selectattr('state', 'eq', entity1_status) | list %}
            {% if matching_entities | length > 0 %}
              {% set alerts = alerts + ['\n' + entity1_icon + ' ' + entity1_label + ':'] %}
              {% for entity in matching_entities %}
                {% set alerts = alerts + ['• ' + (entity.attributes.friendly_name or entity.entity_id) + ' (' + entity.state + ')'] %}
              {% endfor %}
            {% endif %}
          {% else %}
            {% if states(entity1_target) == entity1_status %}
              {% set alerts = alerts + ['\n' + entity1_icon + ' ' + entity1_label + ':'] %}
              {% set alerts = alerts + ['• ' + (state_attr(entity1_target, 'friendly_name') or entity1_target) + ' (' + states(entity1_target) + ')'] %}
            {% endif %}
          {% endif %}
        {% endif %}
        
        {# Check Entity 2 #}
        {% if entity2_enable and entity2_target != "" %}
          {% if entity2_target.startswith('group.') %}
            {% set matching_entities = expand(entity2_target) | selectattr('state', 'eq', entity2_status) | list %}
            {% if matching_entities | length > 0 %}
              {% set alerts = alerts + ['\n' + entity2_icon + ' ' + entity2_label + ':'] %}
              {% for entity in matching_entities %}
                {% set alerts = alerts + ['• ' + (entity.attributes.friendly_name or entity.entity_id) + ' (' + entity.state + ')'] %}
              {% endfor %}
            {% endif %}
          {% else %}
            {% if states(entity2_target) == entity2_status %}
              {% set alerts = alerts + ['\n' + entity2_icon + ' ' + entity2_label + ':'] %}
              {% set alerts = alerts + ['• ' + (state_attr(entity2_target, 'friendly_name') or entity2_target) + ' (' + states(entity2_target) + ')'] %}
            {% endif %}
          {% endif %}
        {% endif %}
        
        {# Check Entity 3 #}
        {% if entity3_enable and entity3_target != "" %}
          {% if entity3_target.startswith('group.') %}
            {% set matching_entities = expand(entity3_target) | selectattr('state', 'eq', entity3_status) | list %}
            {% if matching_entities | length > 0 %}
              {% set alerts = alerts + ['\n' + entity3_icon + ' ' + entity3_label + ':'] %}
              {% for entity in matching_entities %}
                {% set alerts = alerts + ['• ' + (entity.attributes.friendly_name or entity.entity_id) + ' (' + entity.state + ')'] %}
              {% endfor %}
            {% endif %}
          {% else %}
            {% if states(entity3_target) == entity3_status %}
              {% set alerts = alerts + ['\n' + entity3_icon + ' ' + entity3_label + ':'] %}
              {% set alerts = alerts + ['• ' + (state_attr(entity3_target, 'friendly_name') or entity3_target) + ' (' + states(entity3_target) + ')'] %}
            {% endif %}
          {% endif %}
        {% endif %}
        
        {{ alerts | join('\n') }}

mode: single

variables:
  entity1_enable: !input entity1_enable
  entity1_target: !input entity1_target
  entity1_status: !input entity1_status
  entity1_label: !input entity1_label
  entity1_icon: !input entity1_icon
  entity2_enable: !input entity2_enable
  entity2_target: !input entity2_target
  entity2_status: !input entity2_status
  entity2_label: !input entity2_label
  entity2_icon: !input entity2_icon
  entity3_enable: !input entity3_enable
  entity3_target: !input entity3_target
  entity3_status: !input entity3_status
  entity3_label: !input entity3_label
  entity3_icon: !input entity3_icon